apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-u4o2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-u4o2
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-u4o2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-u4o2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-u4o2
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qpuw-tenant/rhtap-demo-app/hacbs-test-project-u4o2@sha256:51d47636a66175bee179b99e5cb6cf4adc4392b3bb9d5222266edca33b82a6db
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
