apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-u4o2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qpuw-tenant/rhtap-demo-app/hacbs-test-project-u4o2@sha256:51d47636a66175bee179b99e5cb6cf4adc4392b3bb9d5222266edca33b82a6db
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
