apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-u4o2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qpuw-tenant/rhtap-demo-app/hacbs-test-project-u4o2@sha256:a6add12e1d3b2a005e7d0a92288f4e7a3f2522a3990d1e624d696f1af6981db6
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
